### ISSUE TITLE
factory is not a function

### ISSUE THREAD

**Issue by drewwells** [futuweb/webpack-amdi18n-loader#8]
I'm seeing these errors after upgrading to 0.5.0
```
Module build failed: TypeError: factory is not a function
    at define (evalmachine.<anonymous>:9:16)
    at evalmachine.<anonymous>:10:5
    at ContextifyScript.Script.runInContext (vm.js:37:29)
```

This doesn't happen when switching back to 0.4.0

**Comment by TooBug** [comment]
0.5.1 fixed.

**Comment by drewwells** [comment]
can you tag this as a release? We need that for internal verification.

**Comment by TooBug** [comment]
@drewwells done.

why not use npm module?

**Comment by drewwells** [comment]
we'll use npm, but legal requires us to point to tagged releases 🥇 thanks for pushing it!
